name: Docksal sandbox

on:
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    container:
      image: docksal/ci-agent:base
    env:
      CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
      DOCKSAL_HOST_IP: ${{ secrets.DOCKSAL_HOST_IP }}
      DOCKSAL_HOST_SSH_KEY: ${{ secrets.DOCKSAL_HOST_SSH_KEY }}
      GITHUB_TOKEN: ${{ github.token }}
      REMOTE_CODEBASE_METHOD: git
    steps:
      - name: Build sandbox
        shell: bash
        run: |
          #set -x 
          mkdir p $HOME/build/testing-main
          cd $HOME/build/testing-main
          source build-env
          fin init --name=testing-main --choise=0 --repo=https://github.com/ACAndreiHarea/test.git --branch=main  -y
          sandbox-init
