name: Docksal sandbox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: cloud
    container:
      image: docksal/ci-agent:base
    env:
      CI_SSH_KEY: ${{ secrets.CI_SSH_KEY }}
      DOCKSAL_HOST_IP: ${{ secrets.DOCKSAL_HOST_IP }}
      DOCKSAL_HOST_SSH_KEY: ${{ secrets.DOCKSAL_HOST_SSH_KEY }}
      #GITHUB_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ BGD3OU4TYHYXNNX3WX7MDGLGEEGPQ }}
      REMOTE_CODEBASE_METHOD: git
    steps:
      - name: Build sandbox
        shell: bash
        run: |
          source build-env
          sandbox-init
